name: (sub) Discover Python version

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      pyversion:
        description: A discovered Python version
        value: ${{ jobs.pyversion.outputs.pyversion }}

jobs:
  pyversion:
    name: Discover minimum Python version
    runs-on: ubuntu-latest
    outputs:
      pyversion: ${{ steps.pyversion.outputs.pyversion }}
    steps:
      - name: checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: discover Python version
        id: pyversion
        uses: ./.github/actions/discover_python_version